FROM golang:1.19.9-alpine3.16 as builder

RUN apk add --no-cache make gcc musl-dev linux-headers git jq bash

COPY ./go.mod /app/go.mod
COPY ./go.sum /app/go.sum

COPY ./umi-bindings /app/umi-bindings

WORKDIR /app/umi-node
RUN go mod download -x

COPY ./umi-node /app/umi-node

RUN go build -o ./bin/stateviz ./cmd/stateviz

FROM alpine:3.16

COPY --from=builder /app/umi-node/bin/stateviz /usr/local/bin

CMD ["stateviz"]
